spring.application.name=RespiraFacilAPI
# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/asmadb
spring.datasource.username=postgres
spring.datasource.password=2001
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

